- kind: environment
  name: dev
  data:
    type: csv
    path: s3a://cortex-examples/poker.csv
    schema:
      - card_1_suit
      - card_1_rank
      - card_2_suit
      - card_2_rank
      - card_3_suit
      - card_3_rank
      - card_4_suit
      - card_4_rank
      - card_5_suit
      - card_5_rank
      - class
