- kind: environment
  name: dev
  limit:
    fraction_of_rows: 0.5
    randomize: true
    random_seed: 1
  data:
    type: csv
    path: s3a://cortex-examples/iris.csv
    schema:
      - sepal_length
      - sepal_width
      - petal_length
      - petal_width
      - class

- kind: environment
  name: prod
  data:
    type: parquet
    path: s3a://cortex-examples/iris.parquet
    schema:
      - parquet_column_name: sepal_length
        raw_column_name: sepal_length
      - parquet_column_name: sepal_width
        raw_column_name: sepal_width
      - parquet_column_name: petal_length
        raw_column_name: petal_length
      - parquet_column_name: petal_width
        raw_column_name: petal_width
      - parquet_column_name: class
        raw_column_name: class
