apiVersion: v1
name: security
version: 1.2.2
appVersion: 1.2.2
tillerVersion: ">=2.7.2"
description: Helm chart for istio authentication
keywords:
  - istio
  - security
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
