- kind: environment
  name: dev
  log_level:
    spark: "ALL"
  data:
    type: csv
    path: s3a://cortex-examples/movie-ratings.csv
    csv_config:
      header: true
    schema: [@user_id, @movie_id, @rating, @timestamp]

- kind: raw_column
  name: user_id
  type: STRING_COLUMN

- kind: raw_column
  name: movie_id
  type: STRING_COLUMN

- kind: raw_column
  name: rating
  type: FLOAT_COLUMN
