cortex:
  cluster_name: testing
  region: us-west-2
  bucket: cortex-vishal

  # CORTEX_VERSION
  image_operator: quay.io/cortexlabs/operator:master
  image_manager: quay.io/cortexlabs/manager:master
  image_downloader: quay.io/cortexlabs/downloader:master
  image_request_monitor: quay.io/cortexlabs/request-monitor:master
  image_cluster_autoscaler: quay.io/cortexlabs/cluster-autoscaler:master
  image_metrics_server: quay.io/cortexlabs/metrics-server:master
  image_inferentia: quay.io/cortexlabs/inferentia:master
  image_neuron_rtd: quay.io/cortexlabs/neuron-rtd:master
  image_nvidia: quay.io/cortexlabs/nvidia:master
  image_fluent_bit: quay.io/cortexlabs/fluent-bit:master
  image_statsd: quay.io/cortexlabs/statsd:master
  image_istio_proxy: quay.io/cortexlabs/istio-proxy:master
  image_istio_pilot: quay.io/cortexlabs/istio-pilot:master
  image_google_pause: quay.io/cortexlabs/pause:master

networking:
  istio-discovery:
    pilot:
      hub: quay.io/cortexlabs
      tag: master # CORTEX_VERSION

      # Can be a full hub/image:tag
      image: istio-pilot

global:
  provider: aws

  # Default hub for Istio images.
  # Releases are published to docker hub under 'istio' project.
  # Dev builds from prow are on gcr.io
  hub: quay.io/cortexlabs
  
  # Default tag for Istio images.
  tag: master # CORTEX_VERSION

  proxy:
    image: istio-proxy
